# Generated by Django 5.1.3 on 2025-01-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_escrow_buyer_confirmed_at_escrow_seller_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('seller_confirmed', 'Seller Confirmed'), ('buyer_confirmed', 'Buyer Confirmed'), ('successful', 'Successful'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('escrow_release', 'Escrow Release')], max_length=20),
        ),
    ]
