# Generated by Django 5.1.3 on 2025-01-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_escrow_amount_alter_escrow_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.transaction'),
        ),
    ]
