# Generated by Django 5.1.3 on 2025-01-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_escrow_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
