# Generated by Django 5.1.3 on 2025-01-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_useraccount_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
