# Generated by Django 5.1.3 on 2025-01-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
