# Generated by Django 5.1.3 on 2025-01-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_useraccount_last_login_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login_agent',
            field=models.CharField(blank=True, default='Unknown', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login_location',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
    ]
