# Generated by Django 5.1.3 on 2025-02-03 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=8)),
                ('home_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhome', 'Townhome')], default='house', max_length=10)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='main_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('is_published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtor', to=settings.AUTH_USER_MODEL)),
                ('additional_photos', models.ManyToManyField(blank=True, related_name='additional_photos', to='abrmservices.photo')),
                ('bathroom_photos', models.ManyToManyField(blank=True, related_name='bathroom_photos', to='abrmservices.photo')),
                ('toilet_photos', models.ManyToManyField(blank=True, related_name='toilet_photos', to='abrmservices.photo')),
            ],
        ),
    ]
