# Generated by Django 5.1.3 on 2025-01-22 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtor', models.EmailField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=8)),
                ('home_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhome', 'Townhome')], default='house', max_length=10)),
                ('main_photo', models.ImageField(upload_to='listings/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('is_published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
