# Generated by Django 5.0.1 on 2024-10-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrmservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('full_package', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='house_images/')),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('bedroom', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('house_type', models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('villa', 'Villa'), ('Duplex', 'Duplex')], default='Apartment', max_length=100)),
            ],
        ),
    ]
