# Generated by Django 5.0.1 on 2024-10-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abrmservices', '0002_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='address',
            new_name='location',
        ),
    ]
