# Generated by Django 5.0.1 on 2024-10-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrmservices', '0003_rename_address_listing_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
