# Generated by Django 5.0.1 on 2024-10-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrmservices', '0005_alter_listing_price_alter_listing_sale_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhome', 'Townhome')], default='house', max_length=10),
        ),
    ]
