# Generated by Django 5.1.3 on 2025-01-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abrmservices', '0007_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
