name: Django CI

on:
  push:
    branches:
      - main  # Trigger when pushing to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger for pull requests targeting the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    services:
      postgres:
        image: postgres:13  # Use PostgreSQL 13 for the database
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set Python version for the environment

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure requirements.txt includes Django and dependencies

      - name: Run tests
        run: |
          python manage.py migrate  # Apply migrations
          python manage.py test  # Run tests
